spring:
  application:
    name: call-core
  profiles:
    active: core

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.callcenter: INFO
server:
  port: 8080
